import 'quiz_data.dart';

const Map<String, List<QuizQuestion>> authoredQuizzesPtC2 = <String, List<QuizQuestion>>{
  '1 Samuel#0': <QuizQuestion>[
    QuizQuestion(
      text: 'O que Ana prometeu a Jeová se tivesse um filho?',
      options: <String>[
        'Dedicá-lo ao serviço de Deus por toda a vida',
        'Oferecer a ele metade dos seus bens',
        'Construir um templo',
        'Tornar-se ela mesma sacerdotisa',
      ],
      correctIndex: 0,
      explanation: 'Ana dedica Samuel ao serviço do tabernáculo (1 Samuel 1).',
    ),
    QuizQuestion(
      text: 'Como Jeová chamou o jovem Samuel?',
      options: <String>[
        'Pronunciando seu nome à noite, várias vezes',
        'Por meio de um anjo visível',
        'Por um único sonho',
        'Por uma voz pública',
      ],
      correctIndex: 0,
      explanation: 'Samuel pensa a princípio que é Eli quem o chama (1 Samuel 3).',
    ),
    QuizQuestion(
      text: 'Por que o povo pediu um rei a Samuel?',
      options: <String>[
        'Para ser como as outras nações',
        'Por ordem direta de Jeová',
        'Por causa de uma invasão iminente',
        'Porque Samuel havia proposto isso',
      ],
      correctIndex: 0,
      explanation: 'O povo rejeita o governo direto de Deus (1 Samuel 8).',
    ),
  ],
  '1 Samuel#1': <QuizQuestion>[
    QuizQuestion(
      text: 'Quem Samuel ungiu em segredo como primeiro rei de Israel?',
      options: <String>['Saul', 'Davi', 'Jônatas', 'Abner'],
      correctIndex: 0,
      explanation: 'Samuel unge Saul discretamente (1 Samuel 9-10).',
      type: QuizAnswerType.freeText,
    ),
    QuizQuestion(
      text: 'Por que Samuel anunciou a rejeição de Saul como rei?',
      options: <String>[
        'Saul ofereceu um sacrifício sem esperar por Samuel',
        'Saul perdeu uma batalha',
        'Saul se recusou a reinar',
        'Saul fugiu diante do inimigo',
      ],
      correctIndex: 0,
      explanation: 'Saul desobedece ao oferecer ele mesmo o sacrifício (1 Samuel 13).',
    ),
    QuizQuestion(
      text: 'Por que Saul foi definitivamente rejeitado como rei por Jeová?',
      options: <String>[
        'Ele desobedeceu ao poupar Agague e o melhor do gado',
        'Ele perdeu uma batalha sem importância',
        'Ele envelheceu rápido demais',
        'Ele pediu ajuda a Samuel',
      ],
      correctIndex: 0,
      explanation: 'A desobediência em relação a Amaleque sela sua rejeição (1 Samuel 15).',
    ),
  ],
  '1 Samuel#2': <QuizQuestion>[
    QuizQuestion(
      text: 'Com que arma Davi venceu Golias?',
      options: <String>['Uma funda e uma pedra', 'Uma espada', 'Uma lança', 'As próprias mãos'],
      correctIndex: 0,
      explanation: 'Davi recusa a armadura e usa sua funda (1 Samuel 17).',
      type: QuizAnswerType.wordBank,
      wordBankDistractors: <String>['espada', 'lança', 'escudo'],
    ),
    QuizQuestion(
      text: 'Que sentimento levou Saul a querer matar Davi depois de sua vitória?',
      options: <String>['Ciúme', 'Medo dos filisteus', 'Raiva de Samuel', 'Um conselho de Jônatas'],
      correctIndex: 0,
      explanation: 'Os cânticos de louvor a Davi despertam o ciúme de Saul (1 Samuel 18).',
    ),
    QuizQuestion(
      text: 'Quem ajudou Davi a escapar de Saul, avisando-o do perigo?',
      options: <String>['Jônatas', 'Abner', 'Apenas Samuel', 'Um sacerdote desconhecido'],
      correctIndex: 0,
      explanation: 'Jônatas avisa Davi por meio de um sinal combinado (1 Samuel 20).',
      type: QuizAnswerType.freeText,
    ),
  ],
  '1 Samuel#3': <QuizQuestion>[
    QuizQuestion(
      text: 'O que Davi faz quando tem a chance de matar Saul numa caverna?',
      options: <String>[
        'Ele o poupa e corta apenas uma parte de sua roupa',
        'Ele o mata imediatamente',
        'Ele foge sem fazer nada',
        'Ele negocia a paz',
      ],
      correctIndex: 0,
      explanation: 'Davi se recusa a tocar no "ungido de Jeová" (1 Samuel 24).',
    ),
    QuizQuestion(
      text: 'Quem evitou um conflito entre Davi e Nabal com sua sabedoria?',
      options: <String>['Abigail', 'Mical', 'Uma serva', 'O sumo sacerdote'],
      correctIndex: 0,
      explanation: 'Abigail acalma Davi com provisões (1 Samuel 25).',
      type: QuizAnswerType.freeText,
    ),
    QuizQuestion(
      text: 'Onde Saul e Jônatas morrem na batalha final do livro?',
      options: <String>[
        'No monte Gilboa, contra os filisteus',
        'Em Jerusalém',
        'Em Hebrom',
        'Em Gibeá',
      ],
      correctIndex: 0,
      explanation: 'Saul e seus filhos morrem em Gilboa (1 Samuel 31).',
    ),
  ],
  '2 Samuel#0': <QuizQuestion>[
    QuizQuestion(
      text: 'Como Davi reagiu à morte de Saul e Jônatas?',
      options: <String>[
        'Compôs um cântico de lamento (uma elegia)',
        'Ficou alegre',
        'Ignorou a notícia',
        'Atacou imediatamente',
      ],
      correctIndex: 0,
      explanation: 'Davi compõe "o Cântico do Arco" (2 Samuel 1).',
    ),
    QuizQuestion(
      text: 'Que cidade Davi conquistou para fazer dela sua capital?',
      options: <String>['Jerusalém', 'Hebrom', 'Siló', 'Gibeá'],
      correctIndex: 0,
      explanation: 'Davi toma a fortaleza de Sião (2 Samuel 5).',
      type: QuizAnswerType.freeText,
    ),
    QuizQuestion(
      text: 'Que promessa Jeová fez a Davi por meio do profeta Natã?',
      options: <String>[
        'Um descendente reinaria para sempre',
        'Davi mesmo construiria o templo',
        'Davi viveria eternamente',
        'Davi se tornaria sacerdote',
      ],
      correctIndex: 0,
      explanation: 'O pacto davídico promete uma dinastia eterna (2 Samuel 7).',
    ),
  ],
  '2 Samuel#1': <QuizQuestion>[
    QuizQuestion(
      text: 'Com quem Davi cometeu adultério, o que levou ao assassinato de Urias?',
      options: <String>['Bate-Seba', 'Mical', 'Abigail', 'Tamar'],
      correctIndex: 0,
      explanation: 'Davi manda matar Urias para esconder seu pecado (2 Samuel 11).',
      type: QuizAnswerType.freeText,
      acceptedAnswers: <String>['Betsabá'],
    ),
    QuizQuestion(
      text: 'Como o profeta Natã confrontou Davi sobre seu pecado?',
      options: <String>[
        'Com uma parábola sobre um homem rico e um pobre',
        'Denunciando-o publicamente',
        'Com uma carta anônima',
        'Deixando seu serviço',
      ],
      correctIndex: 0,
      explanation: 'A parábola leva Davi a reconhecer sua culpa (2 Samuel 12).',
    ),
    QuizQuestion(
      text: 'Quem se rebelou contra seu pai Davi para tomar o trono?',
      options: <String>['Absalão', 'Amnom', 'Salomão', 'Adonias'],
      correctIndex: 0,
      explanation: 'Começa a rebelião de Absalão (2 Samuel 15).',
      type: QuizAnswerType.freeText,
    ),
  ],
  '2 Samuel#2': <QuizQuestion>[
    QuizQuestion(
      text: 'Que conselho fez fracassar o plano rápido de Aitofel contra Davi?',
      options: <String>[
        'O de Husai, que permaneceu fiel a Davi',
        'O de Joabe',
        'O de um sacerdote',
        'O de Salomão',
      ],
      correctIndex: 0,
      explanation: 'Husai atrasa o ataque e salva Davi (2 Samuel 17).',
    ),
    QuizQuestion(
      text: 'Como Absalão morreu?',
      options: <String>[
        'Preso pelos cabelos numa árvore, morto por Joabe',
        'Em combate individual contra Davi',
        'Envenenado',
        'No exílio, de velhice',
      ],
      correctIndex: 0,
      explanation: 'Absalão fica pendurado e Joabe o trespassa (2 Samuel 18).',
    ),
    QuizQuestion(
      text: 'Que ato de Davi provocou uma peste sobre Israel perto do fim do livro?',
      options: <String>[
        'Um recenseamento do povo',
        'A construção de um palácio',
        'Um casamento proibido',
        'A recusa de um sacrifício',
      ],
      correctIndex: 0,
      explanation: 'O recenseamento desagrada a Deus e uma peste se segue (2 Samuel 24).',
      type: QuizAnswerType.wordBank,
      wordBankDistractors: <String>['guerra', 'templo', 'tributo'],
    ),
  ],
  '1 Kings#0': <QuizQuestion>[
    QuizQuestion(
      text: 'Quem tentou se apoderar do trono antes da morte de Davi?',
      options: <String>['Adonias', 'Absalão', 'Apenas Joabe', 'Natã'],
      correctIndex: 0,
      explanation: 'Adonias se proclama rei sem o consentimento de Davi (1 Reis 1).',
      type: QuizAnswerType.freeText,
    ),
    QuizQuestion(
      text: 'O que Salomão pede a Jeová logo no início do seu reinado?',
      options: <String>[
        'Um coração compreensivo para julgar o povo',
        'Riqueza acima de tudo',
        'Vitória militar',
        'Uma longa vida sem condições',
      ],
      correctIndex: 0,
      explanation: 'Salomão pede sabedoria, o que agrada a Deus (1 Reis 3).',
    ),
    QuizQuestion(
      text: 'Quem ajudou Salomão a fornecer materiais para construir o templo?',
      options: <String>['Hirão, rei de Tiro', 'O faraó do Egito', 'A rainha de Sabá', 'O rei de Moabe'],
      correctIndex: 0,
      explanation: 'Hirão fornece madeira de cedro e artesãos (1 Reis 5).',
      type: QuizAnswerType.freeText,
      acceptedAnswers: <String>['Hirão'],
    ),
  ],
  '1 Kings#1': <QuizQuestion>[
    QuizQuestion(
      text: 'O que acontece quando o templo é terminado e dedicado?',
      options: <String>[
        'A glória de Jeová enche o templo',
        'Ocorre um terremoto',
        'O povo se revolta',
        'Salomão deixa Jerusalém',
      ],
      correctIndex: 0,
      explanation: 'A nuvem de glória enche a casa (1 Reis 8).',
    ),
    QuizQuestion(
      text: 'Por que o reino de Salomão acabou se enfraquecendo espiritualmente?',
      options: <String>[
        'Suas esposas estrangeiras desviaram seu coração',
        'Ele perdeu uma guerra',
        'Ele foi exilado',
        'Ele ficou sem riqueza',
      ],
      correctIndex: 0,
      explanation: 'A idolatria de suas esposas leva à sua infidelidade (1 Reis 11).',
    ),
    QuizQuestion(
      text: 'O que Jeroboão faz após a divisão do reino para impedir o povo de ir a Jerusalém?',
      options: <String>[
        'Ele coloca bezerros de ouro em Betel e em Dã',
        'Ele destrói todas as estradas',
        'Ele proíbe todo tipo de culto',
        'Ele constrói um novo templo idêntico',
      ],
      correctIndex: 0,
      explanation: 'Jeroboão introduz um culto idólatra rival (1 Reis 12).',
    ),
  ],
  '1 Kings#2': <QuizQuestion>[
    QuizQuestion(
      text: 'Quem anunciou uma seca punitiva ao rei Acabe?',
      options: <String>['Elias', 'Eliseu', 'Miqueias', 'Obadias'],
      correctIndex: 0,
      explanation: 'Elias anuncia a ausência de chuva e de orvalho (1 Reis 17).',
      type: QuizAnswerType.freeText,
    ),
    QuizQuestion(
      text: 'O que aconteceu no desafio no monte Carmelo?',
      options: <String>[
        'O fogo de Jeová consumiu o sacrifício de Elias',
        'Uma chuva repentina caiu primeiro',
        'Os profetas de Baal venceram',
        'Nada aconteceu',
      ],
      correctIndex: 0,
      explanation: 'Jeová responde com fogo diante de todo o Israel (1 Reis 18).',
    ),
    QuizQuestion(
      text: 'Por que Acabe e Jezabel mandaram matar Nabote?',
      options: <String>[
        'Para se apoderarem de sua vinha',
        'Por um crime que ele havia cometido',
        'Por uma dívida não paga',
        'Por ordem de um profeta',
      ],
      correctIndex: 0,
      explanation: 'Jezabel arma um falso julgamento contra Nabote (1 Reis 21).',
    ),
  ],
  '2 Kings#0': <QuizQuestion>[
    QuizQuestion(
      text: 'Como Elias deixou a terra?',
      options: <String>[
        'Levado ao céu num redemoinho',
        'Morreu de velhice',
        'Foi exilado',
        'Desapareceu sem explicação',
      ],
      correctIndex: 0,
      explanation: 'Eliseu vê Elias ser levado por um redemoinho (2 Reis 2).',
      type: QuizAnswerType.wordBank,
      wordBankDistractors: <String>['carro', 'manto', 'Eliseu'],
    ),
    QuizQuestion(
      text: 'Que milagre Eliseu realizou pela mulher sunamita?',
      options: <String>[
        'Trouxe seu filho de volta à vida',
        'Multiplicou seu rebanho',
        'Curou-a da lepra',
        'Reconstruiu sua casa',
      ],
      correctIndex: 0,
      explanation: 'Eliseu ressuscita o filho da sunamita (2 Reis 4).',
    ),
    QuizQuestion(
      text: 'Como Naamã foi curado da lepra?',
      options: <String>[
        'Banhando-se sete vezes no Jordão',
        'Com um unguento especial',
        'Por uma oração coletiva',
        'Por um jejum prolongado',
      ],
      correctIndex: 0,
      explanation: 'Naamã obedece à instrução de Eliseu apesar de seu ceticismo (2 Reis 5).',
      type: QuizAnswerType.wordBank,
      wordBankDistractors: <String>['Naamã', 'água', 'sacerdote'],
    ),
  ],
  '2 Kings#1': <QuizQuestion>[
    QuizQuestion(
      text: 'Como o cerco de Samaria foi levantado de forma inesperada?',
      options: <String>[
        'O exército arameu fugiu, apavorado por um barulho',
        'Um exército aliado chegou',
        'Uma trégua foi assinada',
        'O rei arameu morreu em combate',
      ],
      correctIndex: 0,
      explanation: 'Jeová faz o inimigo ouvir um barulho que o apavora (2 Reis 7).',
    ),
    QuizQuestion(
      text: 'Quem Jeú eliminou para purificar a realeza de Israel?',
      options: <String>[
        'Jorão, Jezabel e a casa de Acabe',
        'Apenas os profetas de Baal',
        'Os reis de Judá',
        'Os assírios',
      ],
      correctIndex: 0,
      explanation: 'Jeú executa o julgamento anunciado contra a casa de Acabe (2 Reis 9-10).',
    ),
    QuizQuestion(
      text: 'Como o jovem Joás foi protegido antes de se tornar rei?',
      options: <String>[
        'Escondido no templo por sua tia',
        'Enviado para o exterior',
        'Criado por um profeta isolado',
        'Protegido pelo exército assírio',
      ],
      correctIndex: 0,
      explanation: 'Joás escapa do massacre de Atalia (2 Reis 11).',
      type: QuizAnswerType.wordBank,
      wordBankDistractors: <String>['Atalia', 'palácio', 'rainha'],
    ),
  ],
  '2 Kings#2': <QuizQuestion>[
    QuizQuestion(
      text: 'O que acontece com o reino do norte (Israel) após o cerco assírio?',
      options: <String>[
        'Samaria cai e o povo é deportado',
        'Ele conquista a Assíria',
        'Ele assina uma paz duradoura',
        'Nada realmente muda',
      ],
      correctIndex: 0,
      explanation: 'A queda de Samaria marca o fim do reino do norte (2 Reis 17).',
    ),
    QuizQuestion(
      text: 'Como Ezequias reagiu à carta ameaçadora de Senaqueribe?',
      options: <String>[
        'Ele a estendeu diante de Jeová e orou',
        'Ele se rendeu sem resistir',
        'Ele fugiu da cidade',
        'Ele ignorou a ameaça',
      ],
      correctIndex: 0,
      explanation: 'A oração de Ezequias precede o livramento milagroso (2 Reis 19).',
    ),
    QuizQuestion(
      text: 'O que aconteceu com o exército assírio que sitiava Jerusalém?',
      options: <String>[
        'Um anjo feriu um grande número deles numa única noite',
        'Foi derrotado em combate',
        'Simplesmente se retirou',
        'Uma epidemia o enfraqueceu lentamente',
      ],
      correctIndex: 0,
      explanation: 'A intervenção divina salva Jerusalém (2 Reis 19).',
    ),
  ],
  '2 Kings#3': <QuizQuestion>[
    QuizQuestion(
      text: 'O que o sumo sacerdote Hilquias descobriu durante o reinado de Josias?',
      options: <String>[
        'O livro da lei, que estava perdido no templo',
        'Um tesouro de ouro',
        'Um túmulo real',
        'Uma nova fonte de água',
      ],
      correctIndex: 0,
      explanation: 'A descoberta impulsiona a reforma religiosa de Josias (2 Reis 22).',
    ),
    QuizQuestion(
      text: 'Que grande festividade Josias celebrou após sua reforma?',
      options: <String>['A Páscoa', 'As Tendas', 'O Pentecostes', 'O Jubileu'],
      correctIndex: 0,
      explanation: 'Uma Páscoa memorável é celebrada (2 Reis 23).',
      type: QuizAnswerType.freeText,
      acceptedAnswers: <String>['Páscoa'],
    ),
    QuizQuestion(
      text: 'Como termina o livro de Reis?',
      options: <String>[
        'Com a queda de Jerusalém e a destruição do templo',
        'Com a coroação de um rei justo e duradouro',
        'Com uma grande vitória militar',
        'Com o retorno imediato do exílio',
      ],
      correctIndex: 0,
      explanation: 'O relato se conclui com o exílio na Babilônia (2 Reis 25).',
    ),
  ],
  '1 Chronicles#0': <QuizQuestion>[
    QuizQuestion(
      text: 'Com que genealogias este livro começa?',
      options: <String>[
        'De Adão até as doze tribos de Israel',
        'Apenas a linhagem de Davi',
        'Somente os sacerdotes',
        'Os reis do Egito',
      ],
      correctIndex: 0,
      explanation: 'As listas remontam a Adão (1 Crônicas 1-2).',
    ),
    QuizQuestion(
      text: 'De que tribo vem a linhagem real de Davi?',
      options: <String>['Judá', 'Levi', 'Benjamim', 'Efraim'],
      correctIndex: 0,
      explanation: 'A genealogia de Judá inclui a casa de Davi (1 Crônicas 2-3).',
      type: QuizAnswerType.freeText,
    ),
    QuizQuestion(
      text: 'Que tribos se estabeleceram a leste do Jordão, segundo essas genealogias?',
      options: <String>[
        'Rúben, Gade e metade de Manassés',
        'Judá e Benjamim',
        'Levi e Simeão',
        'Dã e Naftali',
      ],
      correctIndex: 0,
      explanation: 'Seu território e seus líderes são relembrados (1 Crônicas 5).',
    ),
  ],
  '1 Chronicles#1': <QuizQuestion>[
    QuizQuestion(
      text: 'Por que Uzá morreu ao transportar a Arca?',
      options: <String>[
        'Ele a tocou quando ela escorregava, contrariando as normas divinas',
        'Ele a roubou',
        'Ele se recusou a carregá-la',
        'Ele zombou do cortejo',
      ],
      correctIndex: 0,
      explanation: 'O transporte não seguiu as instruções divinas (1 Crônicas 13).',
    ),
    QuizQuestion(
      text: 'Como a Arca foi finalmente transportada corretamente para Jerusalém?',
      options: <String>[
        'Carregada pelos levitas, como a lei determinava',
        'Sobre um carro puxado por bois',
        'De barco',
        'Pelos sacerdotes egípcios',
      ],
      correctIndex: 0,
      explanation: 'Davi corrige o erro anterior (1 Crônicas 15).',
    ),
    QuizQuestion(
      text: 'Contra quem Davi obteve vitórias notáveis nesses capítulos?',
      options: <String>[
        'Os filisteus',
        'Os egípcios',
        'Os babilônios',
        'Os persas',
      ],
      correctIndex: 0,
      explanation: 'Davi derrota os filisteus várias vezes (1 Crônicas 14).',
      type: QuizAnswerType.freeText,
      acceptedAnswers: <String>['filisteus'],
    ),
  ],
  '1 Chronicles#2': <QuizQuestion>[
    QuizQuestion(
      text: 'Que cântico Asafe compôs na ocasião em que a Arca foi instalada?',
      options: <String>[
        'Um cântico de louvor e ação de graças',
        'Um cântico de luto',
        'Uma profecia de desgraça',
        'Um cântico de guerra',
      ],
      correctIndex: 0,
      explanation: 'Este salmo de louvor é confiado a Asafe (1 Crônicas 16).',
    ),
    QuizQuestion(
      text: 'Por que Davi não pôde construir o templo pessoalmente?',
      options: <String>[
        'Ele havia derramado muito sangue em guerras',
        'Ele não tinha riqueza suficiente',
        'Ele não tinha nenhum plano',
        'O povo se opunha a isso',
      ],
      correctIndex: 0,
      explanation: 'Jeová reserva essa tarefa para Salomão (1 Crônicas 22; 28).',
    ),
    QuizQuestion(
      text: 'Onde Davi comprou o local do futuro templo?',
      options: <String>[
        'A eira de Ornã (Araúna)',
        'Um campo perto de Hebrom',
        'Uma colina em Siló',
        'Um terreno doado por Hirão',
      ],
      correctIndex: 0,
      explanation: 'Davi constrói ali um altar depois da peste (1 Crônicas 21).',
    ),
  ],
  '1 Chronicles#3': <QuizQuestion>[
    QuizQuestion(
      text: 'Como Davi organizou o serviço dos levitas?',
      options: <String>[
        'Em grupos com tarefas específicas bem distribuídas',
        'Eles não tinham nenhuma organização',
        'Um único homem cuidava de tudo',
        'Eles estavam dispensados do serviço',
      ],
      correctIndex: 0,
      explanation: 'Os levitas são divididos por funções (1 Crônicas 23).',
    ),
    QuizQuestion(
      text: 'Que papel os músicos designados por Davi desempenhavam?',
      options: <String>[
        'Profetizar e louvar com instrumentos',
        'Combater na linha de frente',
        'Julgar processos',
        'Ensinar apenas a leitura',
      ],
      correctIndex: 0,
      explanation: 'Asafe, Hemã e Jedutum dirigem a música sagrada (1 Crônicas 25).',
      type: QuizAnswerType.wordBank,
      wordBankDistractors: <String>['sacrifícios', 'portões', 'tesouro'],
    ),
    QuizQuestion(
      text: 'Qual foi a última grande ação pública de Davi antes de morrer?',
      options: <String>[
        'Encarregar Salomão e o povo de construir o templo',
        'Liderar uma última guerra',
        'Revisar todas as leis',
        'Partir para um exílio voluntário',
      ],
      correctIndex: 0,
      explanation: 'Davi ora e abençoa a assembleia antes de morrer (1 Crônicas 28-29).',
    ),
  ],
  '2 Chronicles#0': <QuizQuestion>[
    QuizQuestion(
      text: 'O que Salomão pede a Jeová no início de seu reinado?',
      options: <String>[
        'Sabedoria e conhecimento para governar',
        'Riqueza acima de tudo',
        'Um exército poderoso',
        'Uma vida sem provações',
      ],
      correctIndex: 0,
      explanation: 'Seu pedido agrada a Deus, que também lhe dá riqueza (2 Crônicas 1).',
      type: QuizAnswerType.wordBank,
      wordBankDistractors: <String>['riqueza', 'vida', 'honra'],
    ),
    QuizQuestion(
      text: 'O que aconteceu quando o templo foi dedicado?',
      options: <String>[
        'O fogo desceu do céu e a glória encheu a casa',
        'Um terremoto destruiu tudo',
        'Nada de especial aconteceu',
        'O povo se dispersou',
      ],
      correctIndex: 0,
      explanation: 'Uma manifestação espetacular confirma a aprovação divina (2 Crônicas 7).',
    ),
    QuizQuestion(
      text: 'Que oração Salomão pronuncia na dedicação?',
      options: <String>[
        'Uma súplica para que Deus ouça as orações feitas voltadas para aquele lugar',
        'Um pedido de mais riqueza',
        'Uma declaração de guerra',
        'Um cântico de luto',
      ],
      correctIndex: 0,
      explanation: 'Salomão pede que Deus ouça desde os céus (2 Crônicas 6).',
    ),
  ],
  '2 Chronicles#1': <QuizQuestion>[
    QuizQuestion(
      text: 'Quem visitou Salomão para testar sua sabedoria?',
      options: <String>[
        'A rainha de Sabá',
        'O rei da Assíria',
        'O faraó do Egito',
        'O rei de Tiro',
      ],
      correctIndex: 0,
      explanation: 'Ela fica impressionada com sua sabedoria e sua riqueza (2 Crônicas 9).',
      type: QuizAnswerType.wordBank,
      wordBankDistractors: <String>['Hirão', 'Egito', 'Salomão'],
    ),
    QuizQuestion(
      text: 'Por que o reino se dividiu sob Roboão?',
      options: <String>[
        'Sua recusa em aliviar o jugo imposto por Salomão',
        'Uma invasão estrangeira',
        'A morte repentina do rei',
        'Um acordo pacífico de divisão',
      ],
      correctIndex: 0,
      explanation: 'Sua dureza leva dez tribos a seguirem Jeroboão (2 Crônicas 10).',
    ),
    QuizQuestion(
      text: 'Como Asa reagiu diante da invasão etíope?',
      options: <String>[
        'Ele orou a Jeová antes da batalha e venceu',
        'Ele se rendeu sem lutar',
        'Ele fugiu com seu exército',
        'Ele pagou um pesado tributo',
      ],
      correctIndex: 0,
      explanation: 'Sua confiança em Deus é recompensada (2 Crônicas 14).',
    ),
  ],
  '2 Chronicles#2': <QuizQuestion>[
    QuizQuestion(
      text: 'Que doença atingiu Asa depois que ele deixou de buscar a Jeová?',
      options: <String>[
        'Uma grave doença nos pés',
        'Lepra',
        'Cegueira',
        'Paralisia total',
      ],
      correctIndex: 0,
      explanation: 'Ele consulta os médicos em vez de Deus (2 Crônicas 16).',
      type: QuizAnswerType.wordBank,
      wordBankDistractors: <String>['lepra', 'olhos', 'febre'],
    ),
    QuizQuestion(
      text: 'Por que Josafá foi repreendido por um profeta?',
      options: <String>[
        'Por sua aliança com o mau rei Acabe',
        'Por ter negligenciado o templo',
        'Por ter se recusado a guerrear',
        'Por ter abolido as festividades',
      ],
      correctIndex: 0,
      explanation: 'Sua aliança com Acabe é criticada (2 Crônicas 19).',
    ),
    QuizQuestion(
      text: 'Como Josafá obteve uma vitória sem combater?',
      options: <String>[
        'Orando, enquanto seus inimigos se matavam entre si',
        'Graças a uma trégua negociada',
        'Por uma fuga estratégica',
        'Graças a um tratado com o Egito',
      ],
      correctIndex: 0,
      explanation: 'A confiança em Deus precede um livramento milagroso (2 Crônicas 20).',
    ),
  ],
  '2 Chronicles#3': <QuizQuestion>[
    QuizQuestion(
      text: 'Como o jovem Joás foi salvo do massacre de Atalia?',
      options: <String>[
        'Escondido no templo por sua tia',
        'Enviado secretamente para o exterior',
        'Adotado por um sacerdote estrangeiro',
        'Protegido por um exército aliado',
      ],
      correctIndex: 0,
      explanation: 'Jeoseba o esconde até sua coroação (2 Crônicas 22-23).',
      type: QuizAnswerType.wordBank,
      wordBankDistractors: <String>['Atalia', 'palácio', 'rainha'],
    ),
    QuizQuestion(
      text: 'Por que Uzias (Azarias) foi atingido pela lepra?',
      options: <String>[
        'Ele quis oferecer incenso, algo reservado aos sacerdotes',
        'Ele se recusou a pagar o dízimo',
        'Ele insultou um profeta',
        'Ele negligenciou o exército',
      ],
      correctIndex: 0,
      explanation: 'Seu orgulho o leva a ultrapassar seu papel (2 Crônicas 26).',
    ),
    QuizQuestion(
      text: 'O que Ezequias faz logo no início de seu reinado?',
      options: <String>[
        'Ele reabre e purifica o templo',
        'Ele declara guerra à Assíria',
        'Ele abole todas as festividades',
        'Ele muda a capital de lugar',
      ],
      correctIndex: 0,
      explanation: 'Ezequias empreende uma grande reforma religiosa (2 Crônicas 29).',
    ),
  ],
  '2 Chronicles#4': <QuizQuestion>[
    QuizQuestion(
      text: 'Que grande festividade Ezequias organizou depois da purificação do templo?',
      options: <String>['Uma Páscoa excepcional', 'As Tendas', 'O Jubileu', 'O Pentecostes'],
      correctIndex: 0,
      explanation: 'Essa Páscoa reúne Judá e parte de Israel (2 Crônicas 30).',
      type: QuizAnswerType.wordBank,
      wordBankDistractors: <String>['festa', 'templo', 'sábado'],
    ),
    QuizQuestion(
      text: 'O que aconteceu depois que Manassés se arrependeu no cativeiro?',
      options: <String>[
        'Jeová o trouxe de volta a Jerusalém e ele fez reformas',
        'Ele permaneceu cativo para sempre',
        'Ele foi executado',
        'Nada mudou',
      ],
      correctIndex: 0,
      explanation: 'Seu arrependimento sincero muda seu destino (2 Crônicas 33).',
    ),
    QuizQuestion(
      text: 'Como termina o livro de Crônicas?',
      options: <String>[
        'Com o decreto de Ciro autorizando o retorno e a reconstrução do templo',
        'Com a destruição final sem esperança',
        'Com a coroação de um novo rei davídico',
        'Com uma guerra civil prolongada',
      ],
      correctIndex: 0,
      explanation: 'O decreto de Ciro abre caminho para o retorno do exílio (2 Crônicas 36).',
    ),
  ],
  'Ezra#0': <QuizQuestion>[
    QuizQuestion(
      text: 'Quem autorizou os exilados a voltar para reconstruir o templo?',
      options: <String>['Ciro, rei da Pérsia', 'Nabucodonosor', 'Apenas Dario', 'Xerxes'],
      correctIndex: 0,
      explanation: 'Ciro publica um decreto libertador (Esdras 1).',
      type: QuizAnswerType.freeText,
      acceptedAnswers: <String>['Ciro'],
    ),
    QuizQuestion(
      text: 'O que os exilados fizeram logo que voltaram, antes mesmo de terminar o templo?',
      options: <String>[
        'Reconstruíram o altar para oferecer sacrifícios',
        'Elegeram um novo rei',
        'Atacaram seus vizinhos',
        'Recusaram todo tipo de culto',
      ],
      correctIndex: 0,
      explanation: 'O altar é restaurado antes dos alicerces (Esdras 3).',
    ),
    QuizQuestion(
      text: 'Que reação mista se seguiu ao lançamento dos alicerces do novo templo?',
      options: <String>[
        'Alegria dos jovens, choro dos idosos que se lembravam do primeiro',
        'Indiferença geral',
        'Raiva unânime',
        'Fuga do povo',
      ],
      correctIndex: 0,
      explanation: 'O contraste com o templo de Salomão emociona os idosos (Esdras 3).',
    ),
  ],
  'Ezra#1': <QuizQuestion>[
    QuizQuestion(
      text: 'Como os trabalhos de reconstrução foram interrompidos?',
      options: <String>[
        'Adversários locais fizeram os trabalhos pararem',
        'Um terremoto destruiu tudo',
        'O povo ficou sem materiais',
        'Os trabalhadores foram embora por conta própria',
      ],
      correctIndex: 0,
      explanation: 'A oposição política bloqueia a obra (Esdras 4).',
    ),
    QuizQuestion(
      text: 'Quem incentivou a retomada dos trabalhos do templo com suas profecias?',
      options: <String>[
        'Ageu e Zacarias',
        'Ezequiel e Daniel',
        'Isaías e Jeremias',
        'Oseias e Amós',
      ],
      correctIndex: 0,
      explanation: 'As mensagens deles fazem a construção ser retomada (Esdras 5).',
      type: QuizAnswerType.wordBank,
      wordBankDistractors: <String>['Esdras', 'Neemias', 'Ciro'],
    ),
    QuizQuestion(
      text: 'Quem chegou mais tarde da Babilônia com um grupo adicional de exilados?',
      options: <String>['Esdras, sacerdote e escriba', 'Neemias', 'Zorobabel', 'Mordecai'],
      correctIndex: 0,
      explanation: 'Esdras chega durante o reinado de Artaxerxes (Esdras 7).',
      type: QuizAnswerType.freeText,
      acceptedAnswers: <String>['Esdras'],
    ),
  ],
  'Ezra#2': <QuizQuestion>[
    QuizQuestion(
      text: 'Por que Esdras não pediu uma escolta armada para a viagem?',
      options: <String>[
        'Ele havia expressado sua confiança na proteção de Deus',
        'O rei havia negado o pedido',
        'A viagem era isenta de perigo',
        'Ele já tinha um exército',
      ],
      correctIndex: 0,
      explanation: 'Esdras havia testemunhado sobre a proteção divina (Esdras 8).',
    ),
    QuizQuestion(
      text: 'Que problema entristeceu profundamente Esdras ao chegar?',
      options: <String>[
        'Casamentos com mulheres das nações vizinhas',
        'Falta de ofertas',
        'Uma fome',
        'Uma guerra civil',
      ],
      correctIndex: 0,
      explanation: 'Esdras rasga suas roupas de tanta dor (Esdras 9).',
      type: QuizAnswerType.wordBank,
      wordBankDistractors: <String>['templo', 'muralha', 'sacerdotes'],
    ),
    QuizQuestion(
      text: 'Como o povo respondeu ao apelo de Esdras?',
      options: <String>[
        'Confessando sua falta e corrigindo a situação',
        'Recusando qualquer mudança',
        'Expulsando Esdras',
        'Ignorando o apelo',
      ],
      correctIndex: 0,
      explanation: 'Uma reforma coletiva acontece (Esdras 10).',
    ),
  ],
  'Nehemiah#0': <QuizQuestion>[
    QuizQuestion(
      text: 'Como Neemias reagiu ao saber do estado das muralhas de Jerusalém?',
      options: <String>[
        'Ele chorou, jejuou e orou',
        'Ele ficou indiferente',
        'Ele renunciou ao seu cargo',
        'Ele organizou uma festa',
      ],
      correctIndex: 0,
      explanation: 'Sua dor o leva a agir (Neemias 1).',
    ),
    QuizQuestion(
      text: 'O que Neemias pediu ao rei Artaxerxes?',
      options: <String>[
        'Permissão para ir reconstruir as muralhas',
        'Ouro para si mesmo',
        'Um cargo mais elevado na corte',
        'Liberdade para deixar o serviço do rei',
      ],
      correctIndex: 0,
      explanation: 'O rei aceita e lhe fornece recursos (Neemias 2).',
      type: QuizAnswerType.wordBank,
      wordBankDistractors: <String>['templo', 'rei', 'Jerusalém'],
    ),
    QuizQuestion(
      text: 'Como os construtores reagiram diante das zombarias e ameaças?',
      options: <String>[
        'Trabalharam com uma mão ocupada e a outra segurando uma arma',
        'Pararam a obra',
        'Fugiram da cidade',
        'Negociaram com os opositores',
      ],
      correctIndex: 0,
      explanation: 'Vigilância e determinação marcam a obra (Neemias 4).',
    ),
  ],
  'Nehemiah#1': <QuizQuestion>[
    QuizQuestion(
      text: 'Que injustiça social Neemias denunciou entre o povo?',
      options: <String>[
        'Empréstimos abusivos que empobreciam os pobres',
        'A recusa de pagar o dízimo',
        'O desrespeito ao sábado somente',
        'A corrupção dos juízes',
      ],
      correctIndex: 0,
      explanation: 'Neemias corrige essa prática injusta (Neemias 5).',
    ),
    QuizQuestion(
      text: 'Em quanto tempo a muralha de Jerusalém foi concluída?',
      options: <String>['52 dias', 'Um ano', 'Dez anos', 'Uma semana'],
      correctIndex: 0,
      explanation: 'Um feito notável apesar de forte oposição (Neemias 6).',
      type: QuizAnswerType.freeText,
      acceptedAnswers: <String>['cinquenta e dois dias', '52'],
    ),
    QuizQuestion(
      text: 'O que aconteceu quando Esdras leu a Lei publicamente para o povo?',
      options: <String>[
        'O povo primeiro chorou, depois celebrou com alegria',
        'O povo se revoltou',
        'Ninguém ouviu',
        'A leitura foi interrompida',
      ],
      correctIndex: 0,
      explanation: 'A Festividade das Cabanas se segue a essa leitura comovente (Neemias 8).',
    ),
  ],
  'Nehemiah#2': <QuizQuestion>[
    QuizQuestion(
      text: 'O que o povo fez depois da leitura da Lei e da confissão nacional?',
      options: <String>[
        'Assinou um compromisso escrito de obedecer a Deus',
        'Deixou Jerusalém',
        'Aboliu as festividades',
        'Exilou os sacerdotes',
      ],
      correctIndex: 0,
      explanation: 'Um pacto por escrito sela esse compromisso (Neemias 9-10).',
    ),
    QuizQuestion(
      text: 'Como a dedicação da muralha foi celebrada?',
      options: <String>[
        'Com procissões de cânticos e ações de graças',
        'Com um jejum silencioso',
        'Com uma cerimônia militar',
        'Fechando os portões',
      ],
      correctIndex: 0,
      explanation: 'Dois coros percorrem a muralha cantando (Neemias 12).',
    ),
    QuizQuestion(
      text: 'Que reforma Neemias impôs ao voltar de um segundo mandato?',
      options: <String>[
        'O respeito rigoroso ao sábado e a expulsão de Tobias',
        'A abolição do templo',
        'Um novo recenseamento',
        'A construção de um palácio',
      ],
      correctIndex: 0,
      explanation: 'Neemias corrige diversos abusos que voltaram em sua ausência (Neemias 13).',
    ),
  ],
};

const Map<String, List<QuizQuestion>> extraQuizzesPtC2 = <String, List<QuizQuestion>>{
  // Nenhuma entrada encontrada em _extraQuizzes para estes livros.
};
